# This is a basic workflow to help you get started with Actions

name: UleskaDemoAction

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v1

      # Runs a single command using the runners shell
      - name: Run Uleska container automation
        run: python3 ${GITHUB_WORKSPACE}/.github/uleska_container.py --application 32551943-9071-4e0d-b419-a32d5ae78e6a --imagename dvwa --tag t1 --url https://github.com/infoslack/docker-dvwa.git

      # Runs a single command using the runners shell
      - name: Run Uleska container automation
        run: python3 ${GITHUB_WORKSPACE}/.github/uleska_container.py --application 32551943-9071-4e0d-b419-a32d5ae78e6a --imagename alpine --tag latest --url https://github.com/infoslack/docker-dvwa.git
